- name: Create lb '{{ cf_lb_entry }}' for tunnel '{{ cf_tunnel.key }}'
  command: "cloudflared tunnel route lb {{ cf_tunnel.key }} {{ cf_lb_entry.hostname }} {{ cf_lb_entry.poolname }}"
  register: create_route
  ignore_errors: true
- name: Show command output
  ansible.builtin.debug:
    msg: "{{ create_route.stdout }}{{ create_route.stderr }}"
